theme = "dark_plus"

[editor]
cursorline = true
line-number = "relative"
auto-format = false
completion-timeout = 5
completion-trigger-len = 1
completion-replace = true
bufferline = "multiple" # "always", "never" or "multiple"
default-line-ending = "lf"
popup-border = "none"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["spinner", "mode", "separator", "version-control"]
center = ["file-absolute-path", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "register", "file-type", "selections", "position", "position-percentage", "file-encoding", "file-line-ending"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
tab = "all"
nbsp = "all"
nnbsp = "all"

[editor.whitespace.characters]
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
# tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "╎", "┆", "┊", "⸽"
skip-levels = 1
